version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'Asia/Makassar'
    groups:
      npm-dependencies:
        patterns:
          - '*'

  - package-ecosystem: 'gradle'
    directory: '/android'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:30'
      timezone: 'Asia/Makassar'
    groups:
      gradle-dependencies:
        patterns:
          - '*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '10:00'
      timezone: 'Asia/Makassar'
    groups:
      github-actions:
        patterns:
          - '*'
